name: Quality Gate

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  quality-gate:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v3

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Run all checks
      run: ./gradlew check

    - name: Generate test coverage report
      run: ./gradlew testDebugUnitTestCoverage || echo "Coverage task not configured, skipping..."

    - name: Comment Test Results on PR
      uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
        name: Quality Gate Test Results
        path: '**/build/test-results/testDebugUnitTest/TEST-*.xml'
        reporter: java-junit
        fail-on-error: true

    - name: Upload coverage reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: coverage-reports
        path: |
          **/build/reports/coverage/
          **/build/reports/jacoco/

    - name: Upload all reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: quality-gate-reports
        path: |
          **/build/reports/
          **/build/test-results/
